travis:
  secure:
    BINSTAR_TOKEN: UA7p3I7jsKs+p2Yqgngli865qtcWY5Z8xA4kzCZ6M0OVPlle3ajYkEpZGs7PvVmumUKSzg0johPy9of53ljyDbWqE3m7MygMfvTEcNXVCStMj0Ik0I11hXV+QMNthDSlzSSHDpM5SmIni0wPYs6LpMNsJm5zpqZFTTepRflQzv9rgTIeWAZbwskhBQOTgdGm+NqIiejfI/JrgUjovtfBE6q2biTz1GpcWSZup/INU+CO5xeeY8R0/yD6TUM/p8/bTiNAJcUy2K10GJ45dXPH+maJoBQ8iaGEbox+Z6qjCaZWnD60UufrsNzMYR3mVwmsaEeivy6MWWn5jw+HxyQtw2kSOzM3rz5Xj2WqJgSfWsakSNTGKlfeQn8/yyYwuvfvaZ0JtjHFNUJGm6QRmSjCNCbMx+QACiGbwacG3sRpSaZKF8uk5IiKfZt0J5NiUnebEnn6nYBpSGxpL2CWM7usCR5G8EeV036WiFRlzB80ppijyQUtwHbYOq86k9ji5rDx0h6krIyPfVNSKKbcVqXxCWWCDEd67sS15kxij8M1fig8NmBoXluxcwYbGX0qt2RtngI27Fw7G7hVaOFC7/eq54fOXbr1IW40dtf3pKiyR3bLB0nUtUNd0qVOFFVZg49lX71MmmqQQ9R/bm8bS0CM6jsqdSj+yqeoO+jTjztpRU4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
